### ISSUE TITLE
Add Switches and Sensor for Streams and more

### ISSUE THREAD

**Issue by bluenazgul** [InTheDaylight14/nginx-proxy-manager-switches#11]
Would it be possible to add Switches for "Streams" and maybe "Redirection Hosts"and "404 Hosts" too?

This way it would me possible to automate Stream forwards and Redirections via Home Assistant.

**Comment by InTheDaylight14** [comment]
Yes, all of those are possible to add. I'll have a release before the end of the year and I can work that in. 

Do you see a need to differentiate between proxy/redirect/stream/404 in the entity IDs?

right now the format is "npm_subdomain_maindomain_com"

But it could change to npm_prox/redir/strm/404_subdomain_com"

A quick test tells me that is not necessary because a domain can only be setup as a proxy or redirect or stream or 404. The same domain cannot be setup as two different things. So I'll probably keep the existing nomenclature.

**Comment by InTheDaylight14** [comment]
Switches to enable/disable Redirection Hosts, Streams, and Dead hosts added in v2.0.0
